name: "📡 Monitor Node.js Nodes"
on: 
  schedule:
    # Run every hour
    - cron: "0 * * * *"

  workflow_dispatch:   

permissions:
  contents: write
  pull-requests: none 
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jenkins Alert and Reporting
        uses: UlisesGascon/jenkins-status-alerts-and-reporting@v1.0.0
        id: jenkins-status-alerts-and-reporting
        with:
          database: monitor/database.json
          jenkins-domain: 'ci.nodejs.org'
          jenkins-username: ${{ secrets.JENKINS_USERNAME }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          # Issues
          generate-issue: true
          issue-assignees: 'UlisesGascon'
          issue-labels: 'incident,monitoring'
          create-issues-for-new-offline-nodes: false
          # Report
          report: monitor/jenkins-report.md
          report-tags-enabled: true
          # Git changes
          auto-commit: true
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Print the Computers
      #   run: |
      #     echo '${{ steps.jenkins-status-alerts-and-reporting.outputs.computers }}'  